### PR TITLE
Fix a bug where `int_in_range` could return out-of-range ints

### LINKED ISSUE #106: int_in_range can return out-of-range values
I was able to get `0` out of `int_in_range(1..=i32::MAX)`, which is less than the minimum specified value of `1`!

Here's what I think is happening in `int_in_range_impl`:

* Suppose when we mod our `result` we get i32::MAX - 1
* We then do a `wrapping_add` of `start` (`1`) to give i32::MAX
* `T::from_widest` then internally mods by i32::MAX to give 0

I'm not too sure of the general fix here, but I worked around this issue by instead using `int_in_range(0..=i32::MAX - 1) + 1`.

### PR DESCRIPTION
**Pull request by fitzgen**
We were adding one to avoid a division by zero, but we already special-casing
and early exiting the only case when the zero could be produced up
above. Removing this addition of one then avoids buggy overflow wrapping when
translating the value from an offset from the range start to the final result
within the range.

I also renamed some variables and added some comments to make the algorithm a
little easier to understand.

Fixes #106

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by fitzgen** [comment]
@Manishearth do you want to take another look at this PR? I refactored the original commit to simplify even more so we can avoid `T::Widest` and all overflows, added a test that we actually do generate everything in the given range eventually, and finally made a new commit to have `int_in_range` not return errors, similar to commit 1d2f653 from PR #53.

**Review by Manishearth — APPROVED** [review]

File: src/unstructured.rs [hunk 1]
```diff
@@ -316,30 +316,48 @@ impl<'a> Unstructured<'a> {
...
         // the underlying data.
         if start == end {
-            return Ok((*start, 0));
+            return Ok((start, 0));
         }
 
-        let range: T::Widest = end.as_widest() - start.as_widest();
-        let mut result = T::Widest::ZERO;
-        let mut offset: usize = 0;
+        let delta = end - start;
```
Comment (Manishearth) [inline src/unstructured.rs:322]: we might need to modify the Int trait to have an associated sized_type int type that we have conversions to/from

Comment (fitzgen) [reply src/unstructured.rs:322]: Not sure I follow what you are suggesting?
